### PR TITLE
Package Logo

### PR DESCRIPTION
**Pull request by 8me**
Not very important, but a logo makes the package look way more professional ;)

### CODE REVIEW

**Comment by tamasgal** [comment]
That's true, let me see ;)

**Comment by 8me** [comment]
As a remark: the important thing is the style of the dot over the i. The text can quickly be changed, after the on-going name discussion has led to a final result :-P

**Comment by tamasgal** [comment]
I don't know what you mean

**Comment by tamasgal** [comment]
Let's go with `Corpuscles.jl`? 😉

**Comment by 8me** [comment]
Yeah let's use `Corpuscles.jl`! Are you doing the rename of the package, @tamasgal? I change the logo then!

**Comment by tamasgal** [comment]
check

**Comment by tamasgal** [comment]
Whatever it looks like ;)

**Comment by tamasgal** [comment]
One which is a bit more "geometrical"?

**Comment by tamasgal** [comment]
Ah no wait, you took the Julia font didn't you? Then it's ok.

Maybe make it a bit squeezed, it's a bit too wide

**Comment by tamasgal** [comment]
Aaaaah stop. You must not change the height or with of a font by any means, that destroys the whole hole geometrical integrity 😱

**Comment by tamasgal** [comment]
Just decrease the letter spacing...

**Comment by tamasgal** [comment]
and put it in `docs/` 😄

**Pull request merged**
