### PR TITLE
Prepare the fancier name with charge and anti-flag

### LINKED ISSUE #32: feat: add charge to the textual name
It is convenient to get particles by their string name rather then id
it would be nice to store the charge in the text identified.

For example:
I would like to call `Sigma(c)(2455)+`, `Sigma(c)(2455)++`, or `Sigma(c)(2455)0`.
Now, all of them are `"Sigma(c)"` in the list
```
filter(p->occursin(r"Sigma\(c*\)", p.name), particles())
```

image

### PR DESCRIPTION
**Pull request by tamasgal**
@mmikhasenko I started a PR but I am in hurry now. I can have a look later hopefully, but if you have time, feel free to jump in ;)

Closes #32

### CODE REVIEW

**Comment by mmikhasenko** [comment]
Thanks a lot, guys.
Could you please post some highlight of the new intended names?

**Comment by 8me** [comment]
> Thanks a lot, guys. Could you please post some highlight of the new intended names?

So the particle gets an '~' in front if its anti particle (in order to make it not that confusing that everything is behind the name). If the charge is an integer (so the name for quarks stays the same) it gets a 0 or the charge as pluses or minuses at the end.

**Comment by tamasgal** [comment]
I think this is kind of what `particle` (https://github.com/scikit-hep/particle), right?

**Comment by 8me** [comment]
btw.: I guess the change the particle name field would require a major version increment as this can change the behavior for scripts selecting particles by name?!

**Comment by 8me** [comment]
> I think this is kind of what `particle` (https://github.com/scikit-hep/particle), right?
> 
> Can you do a usual "before this PR, after this PR" show-off? wink

gimme a moment

**Comment by tamasgal** [comment]
Yep.. That's funny btw. I was literally writing `Corpuscles` code when you commented on this PR and was using

```julia
julia> filter(p->startswith(p.name, "mu"), particles())
2-element Vector{Particle}:
 Particle(-13) mu
 Particle(13) mu
```

I guess with this PR it's

```julia
julia> filter(p->startswith(p.name, "mu"), particles())
2-element Vector{Particle}:
 Particle(-13) mu
 Particle(13) ~mu
```

**Comment by 8me** [comment]
To give an additional example ...
before:
```
julia> p = Particle(2224)
Particle(2224) Delta(1232)
```
after:
```
julia> p = Particle(2224)
Particle(2224) Delta(1232)++
```

**Comment by 8me** [comment]
Hmmm I see some weird behavior if one wants to use e.g.:
´´´
julia> Particle("anti-mu")
Particle(-13) mu+
´´´
which works not anymore because it relies on the name ... so one would need to use:
´´´
julia> Particle("anti-mu-")
Particle(-13) mu+
´´´
which is somehow weird ... maybe we should also keep the "raw" name

**Comment by tamasgal** [comment]
OK, so there are more problems underneath ;)

**Comment by 8me** [comment]
Tried to solve the problem, but feels a little bit quick&dirty ... maybe you can have a look @tamasgal :wink:

**Comment by tamasgal** [comment]
Hmmmm `rawname`... yes, I think keeping track of the original name is fine. We should document that 😉

**Comment by 8me** [comment]
I removed the rawname feature, because the finding with the "rawname" was inconsistent, e.g.:
```
julia> Particle(2224)
Particle(2224) Delta(1232)

julia> Particle(1114)
Particle(1114) Delta(1232)
```

**Comment by tamasgal** [comment]
Alright, let's merge, LGTM :)

**Pull request merged**
